# .github/workflows/build.yml
name: Build Python Executables

on:
  push

jobs:
  # ==================== 构建 Windows ====================
  build-windows:
    if: ${{ !contains(join(github.event.commits.*.message), 'skip') }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          mode: onefile
          show-memory: true
          windows-uac-admin: true
          lto: yes
          windows-console-mode: attach
          python-flag: no_docstrings
          jobs: all
          assume-yes-for-downloads: true

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: mcmdr.exe

  build-windows-x32:
    if: ${{ !contains(join(github.event.commits.*.message), 'skip') }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          architecture: 'x32'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          mode: onefile
          show-memory: true
          windows-uac-admin: true
          lto: yes
          windows-console-mode: attach
          python-flag: no_docstrings
          jobs: all
          assume-yes-for-downloads: true

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-x32
          path: mcmdr-x32.exe

  # ==================== 构建 Linux ====================
  build-linux:
    if: ${{ !contains(join(github.event.commits.*.message), 'skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Linux Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          mode: onefile
          show-memory: true
          jobs: all
          lto: yes
          python-flag: no_docstrings
          assume-yes-for-downloads: true

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux
          path: mcmdr.bin
